[tool.poetry]
name = "colorhash"
version = "1.0.3"
description = ""
authors = ["dimostenis"]

[tool.poetry.dependencies]
python = "^3.3"

[tool.poetry.dev-dependencies]
mypy = "^0.782"
flake8 = "^3.8.3"
black = "^20.8b1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
